Introduce 'forward_alerts' option for routes
grafana/alertmanager pull request #2
Opened 2022-04-18 09:23 UTC by codesome

This PR opens the upstream PR https://github.com/prometheus/alertmanager/pull/2873 here. More details on this is here https://github.com/prometheus/alertmanager/discussions/2886.

Note that this PR is pointing to `for-mimir` branch. @gotjosh and I decided to work with a fork for now until the upstream maintainers take a look at it.

`for-mimir` branch is based on [this commit](https://github.com/grafana/mimir/blob/ba2e9a0ef577c9c6e77885609297a35f000c71e7/go.mod#L33) that Mimir is using right now.

@gotjosh you had some opinions on this to be done via setting existing fields, group_interval and repeat_interval to 0. But I feel that would change the meaning of flags altogether. If you feel strongly about it, I have no objections. But I think we can do better to avoid confusions. Open to other suggestions.

2022-04-18 13:57 UTC, codesome commented
Note that there is no CI set up here. So once we have concluded on the approach, I will take care of it.

2022-04-21 10:08 UTC, gotjosh requested changes

2022-04-21 10:08 UTC, gotjosh commented on config/config.go
> +	ForwardAlerts  bool            `yaml:"forward_alerts,omitempty" json:"forward_alerts,omitempty"`
I don't think a separate option is the way to go.

We'd need to introduce it in Mimir and then remove it if this never makes it upstream. While only dependant on strict marshalling wether old configs would work, we would break two things:

1. The ability to have configs be backwards compatible from Prometheus
2. Someone expecting this to do something and now it does nothing.

An alternative here is to use a special label and provide enough documentation that specifies what this label does:

Overrides the group level timing semantics.

The current check of `ag.hasFlushed` is there as a dedup mechanism to avoid notifying of alerts twice when you're running a Prometheus pair HA setup. 

While I see the whole theme of "forwarding alerts" what you're really saying here is "avoid deduplication and set group timings in a way that a) get the alert delivered as soon as possible and b) never repeat the notification". I would love if we can make that clear in the documentation somewhere. 

With that said, my suggestion is to use a special label (similar to `...`) or `>>>` in honor of ⏩ .

2022-04-21 10:08 UTC, gotjosh commented on config/config.go
> +		r.RepeatInterval = &longDur
When in forwarding mode, I think this is the only setting (and of course `group_by` to `...`) we should auto-set and preferably via a different attribute that ignores the `repeat_interval`. The other two should be set by the user in whichever way they deem fit as they won't affect forwarding mode. 

Concretely:

- Don't set group wait - let the test suite runner do it.
- Don't set group internal  - let the test suite runner do it.
- Use the same attribute of `forwardAlert` to avoid repetition.

2022-04-22 08:57 UTC, gotjosh requested changes

2022-04-22 09:04 UTC, codesome commented on dispatch/dispatch.go
> +			if (ag.opts.ForwardAlerts || a.Resolved()) && got.UpdatedAt == a.UpdatedAt {
If we do not remove the alert from the list, if the repeat_interval kicks in, it will repeat the alert. We don't want to repeat the alert.

2022-07-05 13:42 UTC, closed without merging